name: Create release

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: create-release-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint Workflow
    uses: ./.github/workflows/lint.yml

  deploy:
    name: Create Release
    runs-on: ubuntu-latest
    needs: lint
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/vue-paginate.css,dist/vue-paginate.es.js,dist/vue-paginate.cjs.js,dist/vue-paginate.umd.js,dist/main.d.ts,dist/VuePaginate.d.ts"
