name: Create release

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: create-release-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint Workflow
    uses: ./.github/workflows/lint.yml

  deploy:
    name: Create Release
    runs-on: ubuntu-latest
    needs: lint
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
          scope: '@svifty7'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - uses: ncipollo/release-action@v1

      - name: Release
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
