name: Deploy GitHub Pages

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: deploy-pages-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint Workflow
    uses: ./.github/workflows/lint.yml

  deploy:
    name: Deploy GitHub Pages
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm docs:build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          publish_dir: docs/.vitepress/dist
