name: Pull Request Lint

on:
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize

    branches:
      - main
      - dev

permissions:
  deployments: write
  contents: read
  pages: write
  actions: write
  id-token: write

concurrency:
  group: lint-pr-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  lint-pr:
    name: Lint PR Job
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Lint application
        run: npm run lint:fix
